# yaml-language-server: $schema=schemas/animal-schema.json
animal_id: 0
session:
  number: 1
  duration: 00:10:00
  type: 1
  setup_id: 0
  starting_trial_number: 1
  starting_block_number: 1
  starting_training_level: 1
  last_training_level: 10
sound:
  abl_list:
    - 0
  sound_indexes:
    - index: 2
  cycle_ild: true
fixation_time:
  opto_onset_time:
    min_value: 0
    delta: 0
    target: 0
  sound_onset_time:
    min_value: 0
    delta: 0
    target: 0
reaction_time:
  min_value: 0
  delta: 0
  target: 0
max_reaction_time: 0
lnp_time:
  min_value: 0
  delta: 0
  target: 0
base_reward: 25
optogenetics:
  use_opto: false
  duration: 1
  use_pulses: false
  ramp_time: 0
  frequency: 1
  pulse_duration: 0
autobias_correction: false