# yaml-language-server: $schema=schemas/animal-schema.json
animal_id: 0
session:
  number: 1
  duration: 02:00:00
  type: 1
  setup_id: 0
  starting_trial_number: 1
  starting_block_number: 1
  starting_training_level: 1
  last_training_level: 10
sound:
  fixed_abl: 50
  abl_list:
    - 20
    - 40
    - 50
  cycle_ild: true
fixation_time:
  opto_onset_time:
    min_value: 5
    delta: 0.5
    target: 5
  sound_onset_time:
    min_value: 5
    delta: 0.5
    target: 5
reaction_time:
  min_value: 0.01
  delta: 0.001
  target: 0.01
max_reaction_time: 10
min_movement_time: 0.01
lnp_time:
  min_value: 0.01
  delta: 0.001
  target: 0.01
base_reward: 25
optogenetics:
  use_opto: false
  voltage: 1000
  duration: 2
  opto_ratio: 0.3
  use_pulses: true
  ramp_time: 50
  frequency: 20
  pulse_duration: 20
  use_rt: true
autobias_correction: false