# yaml-language-server: $schema=schemas/config-schema.json
animal_path: C:/Users/HSP/Documents/BonsaiWorkflows/CDC.SoundLateralizationTask/config/animal.yml
behavior_port: COM74
currentdriver_port: COM0
left_pump_port: COM0
output_path: C:/Users/HSP/Documents/BonsaiWorkflows/CDC.SoundLateralizationTask/output
right_pump_port: COM0
setup_path: C:/Users/HSP/Documents/BonsaiWorkflows/CDC.SoundLateralizationTask/config/setup.csv
soundcard_port: COM17
training_path: C:/Users/HSP/Documents/BonsaiWorkflows/CDC.SoundLateralizationTask/config/training.csv
