# yaml-language-server: $schema=schemas/config-schema.json
paths:
  animal: C:/Users/HSP/Documents/BonsaiWorkflows/CDC.SoundLateralizationTask/config/animal.yml
  output: C:/Users/HSP/Documents/BonsaiWorkflows/CDC.SoundLateralizationTask/output
  setup: C:/Users/HSP/Documents/BonsaiWorkflows/CDC.SoundLateralizationTask/config/setup.csv
  training: C:/Users/HSP/Documents/BonsaiWorkflows/CDC.SoundLateralizationTask/config/training.csv
ports:
  behavior: COM74
  currentdriver: COM0
  left_pump: COM0
  right_pump: COM0
  soundcard: COM17
