//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Animal
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class AutobiasCorrection
    {
    
        private bool _useCorrection;
    
        private int _window;
    
        private double _cutoffBias;
    
        private double _performanceThreshold;
    
        private double _slopeMultiplier;
    
        public AutobiasCorrection()
        {
            _useCorrection = false;
        }
    
        protected AutobiasCorrection(AutobiasCorrection other)
        {
            _useCorrection = other._useCorrection;
            _window = other._window;
            _cutoffBias = other._cutoffBias;
            _performanceThreshold = other._performanceThreshold;
            _slopeMultiplier = other._slopeMultiplier;
        }
    
        /// <summary>
        /// Indicates whether the autobias correction feature should be used or not.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("use_correction")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="use_correction")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the autobias correction feature should be used or not.")]
        public bool UseCorrection
        {
            get
            {
                return _useCorrection;
            }
            set
            {
                _useCorrection = value;
            }
        }
    
        /// <summary>
        /// The amount of trials to consider to calculate the animal bias.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("window", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="window")]
        [System.ComponentModel.DescriptionAttribute("The amount of trials to consider to calculate the animal bias.")]
        public int Window
        {
            get
            {
                return _window;
            }
            set
            {
                _window = value;
            }
        }
    
        /// <summary>
        /// The minimum |bias| value from which the side rewards start to be corrected.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("cutoff_bias", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="cutoff_bias")]
        [System.ComponentModel.DescriptionAttribute("The minimum |bias| value from which the side rewards start to be corrected.")]
        public double CutoffBias
        {
            get
            {
                return _cutoffBias;
            }
            set
            {
                _cutoffBias = value;
            }
        }
    
        /// <summary>
        /// The minimum performance value for which the side rewards are not corrected.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("performance_threshold", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="performance_threshold")]
        [System.ComponentModel.DescriptionAttribute("The minimum performance value for which the side rewards are not corrected.")]
        public double PerformanceThreshold
        {
            get
            {
                return _performanceThreshold;
            }
            set
            {
                _performanceThreshold = value;
            }
        }
    
        /// <summary>
        /// A multiplying factor to the slope of the increasing reward amount side (corresponds to the non-biased side).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("slope_multiplier", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="slope_multiplier")]
        [System.ComponentModel.DescriptionAttribute("A multiplying factor to the slope of the increasing reward amount side (correspon" +
            "ds to the non-biased side).")]
        public double SlopeMultiplier
        {
            get
            {
                return _slopeMultiplier;
            }
            set
            {
                _slopeMultiplier = value;
            }
        }
    
        public System.IObservable<AutobiasCorrection> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new AutobiasCorrection(this)));
        }
    
        public System.IObservable<AutobiasCorrection> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new AutobiasCorrection(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("UseCorrection = " + _useCorrection + ", ");
            stringBuilder.Append("Window = " + _window + ", ");
            stringBuilder.Append("CutoffBias = " + _cutoffBias + ", ");
            stringBuilder.Append("PerformanceThreshold = " + _performanceThreshold + ", ");
            stringBuilder.Append("SlopeMultiplier = " + _slopeMultiplier);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class BiasedBlockDistribution
    {
    
        private int _mean;
    
        private int _minValue;
    
        private int _maxValue;
    
        public BiasedBlockDistribution()
        {
        }
    
        protected BiasedBlockDistribution(BiasedBlockDistribution other)
        {
            _mean = other._mean;
            _minValue = other._minValue;
            _maxValue = other._maxValue;
        }
    
        /// <summary>
        /// The mean number of trials a biased block should have.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("mean", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="mean")]
        [System.ComponentModel.DescriptionAttribute("The mean number of trials a biased block should have.")]
        public int Mean
        {
            get
            {
                return _mean;
            }
            set
            {
                _mean = value;
            }
        }
    
        /// <summary>
        /// The minimum number of trials that a biased block should have.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("min_value", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="min_value")]
        [System.ComponentModel.DescriptionAttribute("The minimum number of trials that a biased block should have.")]
        public int MinValue
        {
            get
            {
                return _minValue;
            }
            set
            {
                _minValue = value;
            }
        }
    
        /// <summary>
        /// The maximum number of trials that a biased block should have.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("max_value", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="max_value")]
        [System.ComponentModel.DescriptionAttribute("The maximum number of trials that a biased block should have.")]
        public int MaxValue
        {
            get
            {
                return _maxValue;
            }
            set
            {
                _maxValue = value;
            }
        }
    
        public System.IObservable<BiasedBlockDistribution> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new BiasedBlockDistribution(this)));
        }
    
        public System.IObservable<BiasedBlockDistribution> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new BiasedBlockDistribution(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Mean = " + _mean + ", ");
            stringBuilder.Append("MinValue = " + _minValue + ", ");
            stringBuilder.Append("MaxValue = " + _maxValue);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class BiasedSession
    {
    
        private bool _isBiasedSession;
    
        private double _biasProbability;
    
        private BiasedBlockDistribution _blockDistributions;
    
        public BiasedSession()
        {
            _isBiasedSession = false;
            _blockDistributions = new BiasedBlockDistribution();
        }
    
        protected BiasedSession(BiasedSession other)
        {
            _isBiasedSession = other._isBiasedSession;
            _biasProbability = other._biasProbability;
            _blockDistributions = other._blockDistributions;
        }
    
        /// <summary>
        /// Indicates whether the current session will have biased blocks.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("is_biased_session")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="is_biased_session")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the current session will have biased blocks.")]
        public bool IsBiasedSession
        {
            get
            {
                return _isBiasedSession;
            }
            set
            {
                _isBiasedSession = value;
            }
        }
    
        /// <summary>
        /// The probability of the preferencial side in a biased block.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("bias_probability", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="bias_probability")]
        [System.ComponentModel.DescriptionAttribute("The probability of the preferencial side in a biased block.")]
        public double BiasProbability
        {
            get
            {
                return _biasProbability;
            }
            set
            {
                _biasProbability = value;
            }
        }
    
        /// <summary>
        /// Contains the parameters of the exponential distribution from which the number of trials in a biased block is sampled.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("block_distributions", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="block_distributions")]
        [System.ComponentModel.DescriptionAttribute("Contains the parameters of the exponential distribution from which the number of " +
            "trials in a biased block is sampled.")]
        public BiasedBlockDistribution BlockDistributions
        {
            get
            {
                return _blockDistributions;
            }
            set
            {
                _blockDistributions = value;
            }
        }
    
        public System.IObservable<BiasedSession> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new BiasedSession(this)));
        }
    
        public System.IObservable<BiasedSession> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new BiasedSession(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("IsBiasedSession = " + _isBiasedSession + ", ");
            stringBuilder.Append("BiasProbability = " + _biasProbability + ", ");
            stringBuilder.Append("BlockDistributions = " + _blockDistributions);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class FixationTime
    {
    
        private TimeConstrains _optoOnsetTime;
    
        private TimeConstrains _soundOnsetTime;
    
        public FixationTime()
        {
            _optoOnsetTime = new TimeConstrains();
            _soundOnsetTime = new TimeConstrains();
        }
    
        protected FixationTime(FixationTime other)
        {
            _optoOnsetTime = other._optoOnsetTime;
            _soundOnsetTime = other._soundOnsetTime;
        }
    
        /// <summary>
        /// Contains parameters related to the Optogenetics Onset Time part of the Fixation Time. The units of each of the parameters is milliseconds.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("opto_onset_time")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="opto_onset_time")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the Optogenetics Onset Time part of the Fixation T" +
            "ime. The units of each of the parameters is milliseconds.")]
        public TimeConstrains OptoOnsetTime
        {
            get
            {
                return _optoOnsetTime;
            }
            set
            {
                _optoOnsetTime = value;
            }
        }
    
        /// <summary>
        /// Contains parameters related to the Sound Onset Time part of the Fixation Time. The units of each of the parameters is milliseconds.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("sound_onset_time")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="sound_onset_time")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the Sound Onset Time part of the Fixation Time. Th" +
            "e units of each of the parameters is milliseconds.")]
        public TimeConstrains SoundOnsetTime
        {
            get
            {
                return _soundOnsetTime;
            }
            set
            {
                _soundOnsetTime = value;
            }
        }
    
        public System.IObservable<FixationTime> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new FixationTime(this)));
        }
    
        public System.IObservable<FixationTime> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new FixationTime(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("OptoOnsetTime = " + _optoOnsetTime + ", ");
            stringBuilder.Append("SoundOnsetTime = " + _soundOnsetTime);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class OptoLED
    {
    
        private double _voltage;
    
        private double _power;
    
        private OptoLEDMode _mode;
    
        private bool _usePulses;
    
        private int _frequency;
    
        private int _dutyCycle;
    
        public OptoLED()
        {
        }
    
        protected OptoLED(OptoLED other)
        {
            _voltage = other._voltage;
            _power = other._power;
            _mode = other._mode;
            _usePulses = other._usePulses;
            _frequency = other._frequency;
            _dutyCycle = other._dutyCycle;
        }
    
        /// <summary>
        /// The voltage to use in the TTL signal.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("voltage", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="voltage")]
        [System.ComponentModel.DescriptionAttribute("The voltage to use in the TTL signal.")]
        public double Voltage
        {
            get
            {
                return _voltage;
            }
            set
            {
                _voltage = value;
            }
        }
    
        /// <summary>
        /// The power with which the animal is stimulated.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("power", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="power")]
        [System.ComponentModel.DescriptionAttribute("The power with which the animal is stimulated.")]
        public double Power
        {
            get
            {
                return _power;
            }
            set
            {
                _power = value;
            }
        }
    
        /// <summary>
        /// Indicates whether the LED port is being used to control an external LED via TTL or if it's controlling a LED directly with the current sources.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("mode", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="mode")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the LED port is being used to control an external LED via TTL o" +
            "r if it\'s controlling a LED directly with the current sources.")]
        public OptoLEDMode Mode
        {
            get
            {
                return _mode;
            }
            set
            {
                _mode = value;
            }
        }
    
        /// <summary>
        /// Indicates whether the optogenetics protocol uses pulses of light (true) or a continuous emission (false).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("use_pulses", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="use_pulses")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the optogenetics protocol uses pulses of light (true) or a cont" +
            "inuous emission (false).")]
        public bool UsePulses
        {
            get
            {
                return _usePulses;
            }
            set
            {
                _usePulses = value;
            }
        }
    
        /// <summary>
        /// The frequency of the pulses (Hz). It only works when use_pulses is true.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("frequency", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="frequency")]
        [System.ComponentModel.DescriptionAttribute("The frequency of the pulses (Hz). It only works when use_pulses is true.")]
        public int Frequency
        {
            get
            {
                return _frequency;
            }
            set
            {
                _frequency = value;
            }
        }
    
        /// <summary>
        /// The duty cycle of the pulses (%). It only works when use_pulses is true.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("duty_cycle", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="duty_cycle")]
        [System.ComponentModel.DescriptionAttribute("The duty cycle of the pulses (%). It only works when use_pulses is true.")]
        public int DutyCycle
        {
            get
            {
                return _dutyCycle;
            }
            set
            {
                _dutyCycle = value;
            }
        }
    
        public System.IObservable<OptoLED> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new OptoLED(this)));
        }
    
        public System.IObservable<OptoLED> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new OptoLED(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Voltage = " + _voltage + ", ");
            stringBuilder.Append("Power = " + _power + ", ");
            stringBuilder.Append("Mode = " + _mode + ", ");
            stringBuilder.Append("UsePulses = " + _usePulses + ", ");
            stringBuilder.Append("Frequency = " + _frequency + ", ");
            stringBuilder.Append("DutyCycle = " + _dutyCycle);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Optogenetics
    {
    
        private bool _useOpto;
    
        private OptogeneticsMode _mode;
    
        private double _duration;
    
        private double _optoRatio;
    
        private bool _useRt;
    
        private OptogeneticsRampMode _rampMode;
    
        private int _rampTime;
    
        private OptoLED _led0;
    
        private OptoLED _led1;
    
        public Optogenetics()
        {
            _useOpto = false;
            _led0 = new OptoLED();
            _led1 = new OptoLED();
        }
    
        protected Optogenetics(Optogenetics other)
        {
            _useOpto = other._useOpto;
            _mode = other._mode;
            _duration = other._duration;
            _optoRatio = other._optoRatio;
            _useRt = other._useRt;
            _rampMode = other._rampMode;
            _rampTime = other._rampTime;
            _led0 = other._led0;
            _led1 = other._led1;
        }
    
        /// <summary>
        /// Indicates whether optogenetics is used or not.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("use_opto")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="use_opto")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether optogenetics is used or not.")]
        public bool UseOpto
        {
            get
            {
                return _useOpto;
            }
            set
            {
                _useOpto = value;
            }
        }
    
        /// <summary>
        /// Indicates the optogenetics mode used in the current session.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("mode", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="mode")]
        [System.ComponentModel.DescriptionAttribute("Indicates the optogenetics mode used in the current session.")]
        public OptogeneticsMode Mode
        {
            get
            {
                return _mode;
            }
            set
            {
                _mode = value;
            }
        }
    
        /// <summary>
        /// The duration of the optogenetics stimulation/inhibition protocol (s).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("duration", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="duration")]
        [System.ComponentModel.DescriptionAttribute("The duration of the optogenetics stimulation/inhibition protocol (s).")]
        public double Duration
        {
            get
            {
                return _duration;
            }
            set
            {
                _duration = value;
            }
        }
    
        /// <summary>
        /// The ratio of optogenetics trials.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("opto_ratio", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="opto_ratio")]
        [System.ComponentModel.DescriptionAttribute("The ratio of optogenetics trials.")]
        public double OptoRatio
        {
            get
            {
                return _optoRatio;
            }
            set
            {
                _optoRatio = value;
            }
        }
    
        /// <summary>
        /// Indicates whether the optogenetics stimulation/inhibition should stop when the animal leaves the poke (true) or not (false).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("use_rt", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="use_rt")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the optogenetics stimulation/inhibition should stop when the an" +
            "imal leaves the poke (true) or not (false).")]
        public bool UseRt
        {
            get
            {
                return _useRt;
            }
            set
            {
                _useRt = value;
            }
        }
    
        /// <summary>
        /// Indicates the ramp mode used in the optogenetics protocol. It only works if the LED is not configured to use pulses.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("ramp_mode", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ramp_mode")]
        [System.ComponentModel.DescriptionAttribute("Indicates the ramp mode used in the optogenetics protocol. It only works if the L" +
            "ED is not configured to use pulses.")]
        public OptogeneticsRampMode RampMode
        {
            get
            {
                return _rampMode;
            }
            set
            {
                _rampMode = value;
            }
        }
    
        /// <summary>
        /// The duration of the ramp of the optogenetics protocol (ms). It only works when use_pulses is false.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("ramp_time", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ramp_time")]
        [System.ComponentModel.DescriptionAttribute("The duration of the ramp of the optogenetics protocol (ms). It only works when us" +
            "e_pulses is false.")]
        public int RampTime
        {
            get
            {
                return _rampTime;
            }
            set
            {
                _rampTime = value;
            }
        }
    
        /// <summary>
        /// The optogenetics protocol that LED 0 executes.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("led0", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="led0")]
        [System.ComponentModel.DescriptionAttribute("The optogenetics protocol that LED 0 executes.")]
        public OptoLED Led0
        {
            get
            {
                return _led0;
            }
            set
            {
                _led0 = value;
            }
        }
    
        /// <summary>
        /// The optogenetics protocol that LED 1 executes.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("led1", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="led1")]
        [System.ComponentModel.DescriptionAttribute("The optogenetics protocol that LED 1 executes.")]
        public OptoLED Led1
        {
            get
            {
                return _led1;
            }
            set
            {
                _led1 = value;
            }
        }
    
        public System.IObservable<Optogenetics> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Optogenetics(this)));
        }
    
        public System.IObservable<Optogenetics> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Optogenetics(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("UseOpto = " + _useOpto + ", ");
            stringBuilder.Append("Mode = " + _mode + ", ");
            stringBuilder.Append("Duration = " + _duration + ", ");
            stringBuilder.Append("OptoRatio = " + _optoRatio + ", ");
            stringBuilder.Append("UseRt = " + _useRt + ", ");
            stringBuilder.Append("RampMode = " + _rampMode + ", ");
            stringBuilder.Append("RampTime = " + _rampTime + ", ");
            stringBuilder.Append("Led0 = " + _led0 + ", ");
            stringBuilder.Append("Led1 = " + _led1);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class ReactionTime
    {
    
        private double _minValue;
    
        private double _delta;
    
        private double _target;
    
        private double _maxValue;
    
        public ReactionTime()
        {
            _minValue = 0.01D;
            _delta = 0.001D;
            _target = 0.01D;
            _maxValue = 10D;
        }
    
        protected ReactionTime(ReactionTime other)
        {
            _minValue = other._minValue;
            _delta = other._delta;
            _target = other._target;
            _maxValue = other._maxValue;
        }
    
        /// <summary>
        /// The initial base value.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("min_value")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="min_value")]
        [System.ComponentModel.DescriptionAttribute("The initial base value.")]
        public double MinValue
        {
            get
            {
                return _minValue;
            }
            set
            {
                _minValue = value;
            }
        }
    
        /// <summary>
        /// The increment to the base value every trial a certain condition is met until the target value is reached.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("delta")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="delta")]
        [System.ComponentModel.DescriptionAttribute("The increment to the base value every trial a certain condition is met until the " +
            "target value is reached.")]
        public double Delta
        {
            get
            {
                return _delta;
            }
            set
            {
                _delta = value;
            }
        }
    
        /// <summary>
        /// The target value.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("target")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="target")]
        [System.ComponentModel.DescriptionAttribute("The target value.")]
        public double Target
        {
            get
            {
                return _target;
            }
            set
            {
                _target = value;
            }
        }
    
        /// <summary>
        /// The maximum allowed reaction time (s).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("max_value")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="max_value")]
        [System.ComponentModel.DescriptionAttribute("The maximum allowed reaction time (s).")]
        public double MaxValue
        {
            get
            {
                return _maxValue;
            }
            set
            {
                _maxValue = value;
            }
        }
    
        public System.IObservable<ReactionTime> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ReactionTime(this)));
        }
    
        public System.IObservable<ReactionTime> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ReactionTime(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("MinValue = " + _minValue + ", ");
            stringBuilder.Append("Delta = " + _delta + ", ");
            stringBuilder.Append("Target = " + _target + ", ");
            stringBuilder.Append("MaxValue = " + _maxValue);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Reward
    {
    
        private double _baseAmount;
    
        private double _probability;
    
        public Reward()
        {
            _probability = 1D;
        }
    
        protected Reward(Reward other)
        {
            _baseAmount = other._baseAmount;
            _probability = other._probability;
        }
    
        /// <summary>
        /// The amount of reward delivered to the animal (uL).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("base_amount", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="base_amount")]
        [System.ComponentModel.DescriptionAttribute("The amount of reward delivered to the animal (uL).")]
        public double BaseAmount
        {
            get
            {
                return _baseAmount;
            }
            set
            {
                _baseAmount = value;
            }
        }
    
        /// <summary>
        /// The probability of the animal receiving reward given a right answer.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("probability")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="probability")]
        [System.ComponentModel.DescriptionAttribute("The probability of the animal receiving reward given a right answer.")]
        public double Probability
        {
            get
            {
                return _probability;
            }
            set
            {
                _probability = value;
            }
        }
    
        public System.IObservable<Reward> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Reward(this)));
        }
    
        public System.IObservable<Reward> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Reward(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("BaseAmount = " + _baseAmount + ", ");
            stringBuilder.Append("Probability = " + _probability);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Session
    {
    
        private int _number;
    
        private string _experimenter;
    
        private System.TimeSpan _duration;
    
        private int _type;
    
        private int _startingTrialNumber;
    
        private int _blockNumber;
    
        private int _startingTrainingLevel;
    
        private int _lastTrainingLevel;
    
        public Session()
        {
        }
    
        protected Session(Session other)
        {
            _number = other._number;
            _experimenter = other._experimenter;
            _duration = other._duration;
            _type = other._type;
            _startingTrialNumber = other._startingTrialNumber;
            _blockNumber = other._blockNumber;
            _startingTrainingLevel = other._startingTrainingLevel;
            _lastTrainingLevel = other._lastTrainingLevel;
        }
    
        /// <summary>
        /// The number of the current session.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("number", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="number")]
        [System.ComponentModel.DescriptionAttribute("The number of the current session.")]
        public int Number
        {
            get
            {
                return _number;
            }
            set
            {
                _number = value;
            }
        }
    
        /// <summary>
        /// The person who trained the animal in the current session.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("experimenter", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="experimenter")]
        [System.ComponentModel.DescriptionAttribute("The person who trained the animal in the current session.")]
        public string Experimenter
        {
            get
            {
                return _experimenter;
            }
            set
            {
                _experimenter = value;
            }
        }
    
        /// <summary>
        /// The duration of the session (in the hh:mm:ss format).
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("duration", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="duration")]
        [System.ComponentModel.DescriptionAttribute("The duration of the session (in the hh:mm:ss format).")]
        public System.TimeSpan Duration
        {
            get
            {
                return _duration;
            }
            set
            {
                _duration = value;
            }
        }
    
        [Newtonsoft.Json.JsonIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlIgnoreAttribute()]
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Duration")]
        public string DurationXml
        {
            get
            {
                return System.Xml.XmlConvert.ToString(_duration);
            }
            set
            {
                _duration = System.Xml.XmlConvert.ToTimeSpan(value);
            }
        }
    
        /// <summary>
        /// The number of the session type.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("type", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="type")]
        [System.ComponentModel.DescriptionAttribute("The number of the session type.")]
        public int Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }
    
        /// <summary>
        /// The number of the first trial of the session.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("starting_trial_number", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="starting_trial_number")]
        [System.ComponentModel.DescriptionAttribute("The number of the first trial of the session.")]
        public int StartingTrialNumber
        {
            get
            {
                return _startingTrialNumber;
            }
            set
            {
                _startingTrialNumber = value;
            }
        }
    
        /// <summary>
        /// The number of the first block of the session.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("block_number", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="block_number")]
        [System.ComponentModel.DescriptionAttribute("The number of the first block of the session.")]
        public int BlockNumber
        {
            get
            {
                return _blockNumber;
            }
            set
            {
                _blockNumber = value;
            }
        }
    
        /// <summary>
        /// The training level the animal will start in the current session.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("starting_training_level", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="starting_training_level")]
        [System.ComponentModel.DescriptionAttribute("The training level the animal will start in the current session.")]
        public int StartingTrainingLevel
        {
            get
            {
                return _startingTrainingLevel;
            }
            set
            {
                _startingTrainingLevel = value;
            }
        }
    
        /// <summary>
        /// The last training level the animal is allowed to progress to in the current session.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("last_training_level", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="last_training_level")]
        [System.ComponentModel.DescriptionAttribute("The last training level the animal is allowed to progress to in the current sessi" +
            "on.")]
        public int LastTrainingLevel
        {
            get
            {
                return _lastTrainingLevel;
            }
            set
            {
                _lastTrainingLevel = value;
            }
        }
    
        public System.IObservable<Session> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Session(this)));
        }
    
        public System.IObservable<Session> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Session(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Number = " + _number + ", ");
            stringBuilder.Append("Experimenter = " + _experimenter + ", ");
            stringBuilder.Append("Duration = " + _duration + ", ");
            stringBuilder.Append("Type = " + _type + ", ");
            stringBuilder.Append("StartingTrialNumber = " + _startingTrialNumber + ", ");
            stringBuilder.Append("BlockNumber = " + _blockNumber + ", ");
            stringBuilder.Append("StartingTrainingLevel = " + _startingTrainingLevel + ", ");
            stringBuilder.Append("LastTrainingLevel = " + _lastTrainingLevel);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Sound
    {
    
        private bool _pseudoRandomSide;
    
        private int _maxSide;
    
        private bool _ablBlock;
    
        private double _shortDurationRatio;
    
        public Sound()
        {
            _ablBlock = false;
            _shortDurationRatio = 0D;
        }
    
        protected Sound(Sound other)
        {
            _pseudoRandomSide = other._pseudoRandomSide;
            _maxSide = other._maxSide;
            _ablBlock = other._ablBlock;
            _shortDurationRatio = other._shortDurationRatio;
        }
    
        /// <summary>
        /// Indicates whether the correct side is picked pseudo-randomly (true) or randomly (false). If it's picked pseudo-randomly, a shuffled array with equal amounts of -1's (left) and 1's (right) of size 2 * `max_side` is created and it's cycled through - a new shuffled array is generated when the end of the array is reached.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("pseudo_random_side", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="pseudo_random_side")]
        [System.ComponentModel.DescriptionAttribute(@"Indicates whether the correct side is picked pseudo-randomly (true) or randomly (false). If it's picked pseudo-randomly, a shuffled array with equal amounts of -1's (left) and 1's (right) of size 2 * `max_side` is created and it's cycled through - a new shuffled array is generated when the end of the array is reached.")]
        public bool PseudoRandomSide
        {
            get
            {
                return _pseudoRandomSide;
            }
            set
            {
                _pseudoRandomSide = value;
            }
        }
    
        /// <summary>
        /// The maximum amount of elements representing the left or right side in the pseudo-random array for when the side is picked pseudo-randomly.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("max_side", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="max_side")]
        [System.ComponentModel.DescriptionAttribute("The maximum amount of elements representing the left or right side in the pseudo-" +
            "random array for when the side is picked pseudo-randomly.")]
        public int MaxSide
        {
            get
            {
                return _maxSide;
            }
            set
            {
                _maxSide = value;
            }
        }
    
        /// <summary>
        /// Indicates whether the the same ABL should be used across the current block.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("abl_block")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="abl_block")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the the same ABL should be used across the current block.")]
        public bool AblBlock
        {
            get
            {
                return _ablBlock;
            }
            set
            {
                _ablBlock = value;
            }
        }
    
        /// <summary>
        /// The percentage of short duration trials in a session.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("short_duration_ratio")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="short_duration_ratio")]
        [System.ComponentModel.DescriptionAttribute("The percentage of short duration trials in a session.")]
        public double ShortDurationRatio
        {
            get
            {
                return _shortDurationRatio;
            }
            set
            {
                _shortDurationRatio = value;
            }
        }
    
        public System.IObservable<Sound> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Sound(this)));
        }
    
        public System.IObservable<Sound> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Sound(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("PseudoRandomSide = " + _pseudoRandomSide + ", ");
            stringBuilder.Append("MaxSide = " + _maxSide + ", ");
            stringBuilder.Append("AblBlock = " + _ablBlock + ", ");
            stringBuilder.Append("ShortDurationRatio = " + _shortDurationRatio);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class TimeConstrains
    {
    
        private double _minValue;
    
        private double _delta;
    
        private double _target;
    
        public TimeConstrains()
        {
            _minValue = 0.01D;
            _delta = 0.001D;
            _target = 0.01D;
        }
    
        protected TimeConstrains(TimeConstrains other)
        {
            _minValue = other._minValue;
            _delta = other._delta;
            _target = other._target;
        }
    
        /// <summary>
        /// The initial base value.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("min_value")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="min_value")]
        [System.ComponentModel.DescriptionAttribute("The initial base value.")]
        public double MinValue
        {
            get
            {
                return _minValue;
            }
            set
            {
                _minValue = value;
            }
        }
    
        /// <summary>
        /// The increment to the base value every trial a certain condition is met until the target value is reached.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("delta")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="delta")]
        [System.ComponentModel.DescriptionAttribute("The increment to the base value every trial a certain condition is met until the " +
            "target value is reached.")]
        public double Delta
        {
            get
            {
                return _delta;
            }
            set
            {
                _delta = value;
            }
        }
    
        /// <summary>
        /// The target value.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("target")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="target")]
        [System.ComponentModel.DescriptionAttribute("The target value.")]
        public double Target
        {
            get
            {
                return _target;
            }
            set
            {
                _target = value;
            }
        }
    
        public System.IObservable<TimeConstrains> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new TimeConstrains(this)));
        }
    
        public System.IObservable<TimeConstrains> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new TimeConstrains(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("MinValue = " + _minValue + ", ");
            stringBuilder.Append("Delta = " + _delta + ", ");
            stringBuilder.Append("Target = " + _target);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Animal
    {
    
        private string _animalId;
    
        private string _batch;
    
        private Session _session;
    
        private Sound _sound;
    
        private FixationTime _fixationTime;
    
        private ReactionTime _reactionTime;
    
        private double _minMovementTime;
    
        private TimeConstrains _lnpTime;
    
        private Reward _reward;
    
        private Optogenetics _optogenetics;
    
        private AutobiasCorrection _autobiasCorrection;
    
        private BiasedSession _biasedSession;
    
        public Animal()
        {
            _session = new Session();
            _sound = new Sound();
            _fixationTime = new FixationTime();
            _reactionTime = new ReactionTime();
            _minMovementTime = 0.01D;
            _lnpTime = new TimeConstrains();
            _reward = new Reward();
            _optogenetics = new Optogenetics();
            _autobiasCorrection = new AutobiasCorrection();
            _biasedSession = new BiasedSession();
        }
    
        protected Animal(Animal other)
        {
            _animalId = other._animalId;
            _batch = other._batch;
            _session = other._session;
            _sound = other._sound;
            _fixationTime = other._fixationTime;
            _reactionTime = other._reactionTime;
            _minMovementTime = other._minMovementTime;
            _lnpTime = other._lnpTime;
            _reward = other._reward;
            _optogenetics = other._optogenetics;
            _autobiasCorrection = other._autobiasCorrection;
            _biasedSession = other._biasedSession;
        }
    
        /// <summary>
        /// The ID of the animal.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("animal_id", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="animal_id")]
        [System.ComponentModel.DescriptionAttribute("The ID of the animal.")]
        public string AnimalId
        {
            get
            {
                return _animalId;
            }
            set
            {
                _animalId = value;
            }
        }
    
        /// <summary>
        /// The batch to which the current animal belongs to.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("batch", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="batch")]
        [System.ComponentModel.DescriptionAttribute("The batch to which the current animal belongs to.")]
        public string Batch
        {
            get
            {
                return _batch;
            }
            set
            {
                _batch = value;
            }
        }
    
        /// <summary>
        /// Contains the session-related parameters.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("session", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="session")]
        [System.ComponentModel.DescriptionAttribute("Contains the session-related parameters.")]
        public Session Session
        {
            get
            {
                return _session;
            }
            set
            {
                _session = value;
            }
        }
    
        /// <summary>
        /// Contains the sound-related parameters.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("sound", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="sound")]
        [System.ComponentModel.DescriptionAttribute("Contains the sound-related parameters.")]
        public Sound Sound
        {
            get
            {
                return _sound;
            }
            set
            {
                _sound = value;
            }
        }
    
        /// <summary>
        /// Contains parameters related to the fixation time.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("fixation_time", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="fixation_time")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the fixation time.")]
        public FixationTime FixationTime
        {
            get
            {
                return _fixationTime;
            }
            set
            {
                _fixationTime = value;
            }
        }
    
        /// <summary>
        /// Contains parameters related to the reaction time. The units of each of the parameters is seconds.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("reaction_time")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="reaction_time")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the reaction time. The units of each of the parame" +
            "ters is seconds.")]
        public ReactionTime ReactionTime
        {
            get
            {
                return _reactionTime;
            }
            set
            {
                _reactionTime = value;
            }
        }
    
        /// <summary>
        /// The minimum allowed movement time (s).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("min_movement_time")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="min_movement_time")]
        [System.ComponentModel.DescriptionAttribute("The minimum allowed movement time (s).")]
        public double MinMovementTime
        {
            get
            {
                return _minMovementTime;
            }
            set
            {
                _minMovementTime = value;
            }
        }
    
        /// <summary>
        /// Contains parameters related to the LNP (Lateral Nose Poke) time. The units of each of the parameters is seconds.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("lnp_time")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="lnp_time")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the LNP (Lateral Nose Poke) time. The units of eac" +
            "h of the parameters is seconds.")]
        public TimeConstrains LnpTime
        {
            get
            {
                return _lnpTime;
            }
            set
            {
                _lnpTime = value;
            }
        }
    
        /// <summary>
        /// Contains the parameters that configure the reward delivery.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("reward", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="reward")]
        [System.ComponentModel.DescriptionAttribute("Contains the parameters that configure the reward delivery.")]
        public Reward Reward
        {
            get
            {
                return _reward;
            }
            set
            {
                _reward = value;
            }
        }
    
        /// <summary>
        /// Contains the optogenetics-related parameters.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("optogenetics")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="optogenetics")]
        [System.ComponentModel.DescriptionAttribute("Contains the optogenetics-related parameters.")]
        public Optogenetics Optogenetics
        {
            get
            {
                return _optogenetics;
            }
            set
            {
                _optogenetics = value;
            }
        }
    
        /// <summary>
        /// Contains parameters related to the autobias correction algorithm.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("autobias_correction")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="autobias_correction")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the autobias correction algorithm.")]
        public AutobiasCorrection AutobiasCorrection
        {
            get
            {
                return _autobiasCorrection;
            }
            set
            {
                _autobiasCorrection = value;
            }
        }
    
        /// <summary>
        /// Contains the parameter to configure a biased session.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("biased_session")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="biased_session")]
        [System.ComponentModel.DescriptionAttribute("Contains the parameter to configure a biased session.")]
        public BiasedSession BiasedSession
        {
            get
            {
                return _biasedSession;
            }
            set
            {
                _biasedSession = value;
            }
        }
    
        public System.IObservable<Animal> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Animal(this)));
        }
    
        public System.IObservable<Animal> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Animal(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("AnimalId = " + _animalId + ", ");
            stringBuilder.Append("Batch = " + _batch + ", ");
            stringBuilder.Append("Session = " + _session + ", ");
            stringBuilder.Append("Sound = " + _sound + ", ");
            stringBuilder.Append("FixationTime = " + _fixationTime + ", ");
            stringBuilder.Append("ReactionTime = " + _reactionTime + ", ");
            stringBuilder.Append("MinMovementTime = " + _minMovementTime + ", ");
            stringBuilder.Append("LnpTime = " + _lnpTime + ", ");
            stringBuilder.Append("Reward = " + _reward + ", ");
            stringBuilder.Append("Optogenetics = " + _optogenetics + ", ");
            stringBuilder.Append("AutobiasCorrection = " + _autobiasCorrection + ", ");
            stringBuilder.Append("BiasedSession = " + _biasedSession);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum OptoLEDMode
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="TTL")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="TTL")]
        TTL = 0,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Current")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Current")]
        Current = 1,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum OptogeneticsMode
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Left")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Left")]
        Left = 0,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Right")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Right")]
        Right = 1,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Bilateral")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Bilateral")]
        Bilateral = 2,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum OptogeneticsRampMode
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="None")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="None")]
        None = 0,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Rise")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Rise")]
        Rise = 1,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Fall")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Fall")]
        Fall = 2,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Both")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Both")]
        Both = 3,
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToJson
    {
    
        public Newtonsoft.Json.Formatting Formatting { get; set; }

        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            var formatting = Formatting;
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value, formatting));
        }

        public System.IObservable<string> Process(System.IObservable<AutobiasCorrection> source)
        {
            return Process<AutobiasCorrection>(source);
        }

        public System.IObservable<string> Process(System.IObservable<BiasedBlockDistribution> source)
        {
            return Process<BiasedBlockDistribution>(source);
        }

        public System.IObservable<string> Process(System.IObservable<BiasedSession> source)
        {
            return Process<BiasedSession>(source);
        }

        public System.IObservable<string> Process(System.IObservable<FixationTime> source)
        {
            return Process<FixationTime>(source);
        }

        public System.IObservable<string> Process(System.IObservable<OptoLED> source)
        {
            return Process<OptoLED>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Optogenetics> source)
        {
            return Process<Optogenetics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<ReactionTime> source)
        {
            return Process<ReactionTime>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Reward> source)
        {
            return Process<Reward>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Session> source)
        {
            return Process<Session>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Sound> source)
        {
            return Process<Sound>(source);
        }

        public System.IObservable<string> Process(System.IObservable<TimeConstrains> source)
        {
            return Process<TimeConstrains>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Animal> source)
        {
            return Process<Animal>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<AutobiasCorrection>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<BiasedBlockDistribution>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<BiasedSession>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<FixationTime>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<OptoLED>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Optogenetics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ReactionTime>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Reward>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Session>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Sound>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<TimeConstrains>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Animal>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<Animal>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<AutobiasCorrection> source)
        {
            return Process<AutobiasCorrection>(source);
        }

        public System.IObservable<string> Process(System.IObservable<BiasedBlockDistribution> source)
        {
            return Process<BiasedBlockDistribution>(source);
        }

        public System.IObservable<string> Process(System.IObservable<BiasedSession> source)
        {
            return Process<BiasedSession>(source);
        }

        public System.IObservable<string> Process(System.IObservable<FixationTime> source)
        {
            return Process<FixationTime>(source);
        }

        public System.IObservable<string> Process(System.IObservable<OptoLED> source)
        {
            return Process<OptoLED>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Optogenetics> source)
        {
            return Process<Optogenetics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<ReactionTime> source)
        {
            return Process<ReactionTime>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Reward> source)
        {
            return Process<Reward>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Session> source)
        {
            return Process<Session>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Sound> source)
        {
            return Process<Sound>(source);
        }

        public System.IObservable<string> Process(System.IObservable<TimeConstrains> source)
        {
            return Process<TimeConstrains>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Animal> source)
        {
            return Process<Animal>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<AutobiasCorrection>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<BiasedBlockDistribution>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<BiasedSession>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<FixationTime>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<OptoLED>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Optogenetics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ReactionTime>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Reward>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Session>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Sound>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<TimeConstrains>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Animal>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<Animal>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}