//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Setup
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Camera
    {
    
        private bool _useCamera;
    
        private CameraType _type;
    
        private double _framesPerSecond;
    
        private string _resolution;
    
        private CameraCodec _codec;
    
        public Camera()
        {
        }
    
        protected Camera(Camera other)
        {
            _useCamera = other._useCamera;
            _type = other._type;
            _framesPerSecond = other._framesPerSecond;
            _resolution = other._resolution;
            _codec = other._codec;
        }
    
        /// <summary>
        /// Indicates whether the setup has a camera (true) or not (false).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("use_camera", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="use_camera")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the setup has a camera (true) or not (false).")]
        public bool UseCamera
        {
            get
            {
                return _useCamera;
            }
            set
            {
                _useCamera = value;
            }
        }
    
        /// <summary>
        /// The type of camera used in the setup.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("type", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="type")]
        [System.ComponentModel.DescriptionAttribute("The type of camera used in the setup.")]
        public CameraType Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }
    
        /// <summary>
        /// The number of frames per second of the camera.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("frames_per_second", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="frames_per_second")]
        [System.ComponentModel.DescriptionAttribute("The number of frames per second of the camera.")]
        public double FramesPerSecond
        {
            get
            {
                return _framesPerSecond;
            }
            set
            {
                _framesPerSecond = value;
            }
        }
    
        /// <summary>
        /// The resolution with which the camera is recording the video.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("resolution", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="resolution")]
        [System.ComponentModel.DescriptionAttribute("The resolution with which the camera is recording the video.")]
        public string Resolution
        {
            get
            {
                return _resolution;
            }
            set
            {
                _resolution = value;
            }
        }
    
        /// <summary>
        /// The codec used to save the video with FFMPEG.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("codec", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="codec")]
        [System.ComponentModel.DescriptionAttribute("The codec used to save the video with FFMPEG.")]
        public CameraCodec Codec
        {
            get
            {
                return _codec;
            }
            set
            {
                _codec = value;
            }
        }
    
        public System.IObservable<Camera> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Camera(this)));
        }
    
        public System.IObservable<Camera> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Camera(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("UseCamera = " + _useCamera + ", ");
            stringBuilder.Append("Type = " + _type + ", ");
            stringBuilder.Append("FramesPerSecond = " + _framesPerSecond + ", ");
            stringBuilder.Append("Resolution = " + _resolution + ", ");
            stringBuilder.Append("Codec = " + _codec);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Lights
    {
    
        private double _boxPeriod;
    
        private double _pokePeriod;
    
        private bool _itiLight;
    
        private bool _pokeLight;
    
        private bool _fixationLight;
    
        private bool _penaltyLight;
    
        public Lights()
        {
        }
    
        protected Lights(Lights other)
        {
            _boxPeriod = other._boxPeriod;
            _pokePeriod = other._pokePeriod;
            _itiLight = other._itiLight;
            _pokeLight = other._pokeLight;
            _fixationLight = other._fixationLight;
            _penaltyLight = other._penaltyLight;
        }
    
        /// <summary>
        /// The period of the blinking of the box LED (ms).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("box_period", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="box_period")]
        [System.ComponentModel.DescriptionAttribute("The period of the blinking of the box LED (ms).")]
        public double BoxPeriod
        {
            get
            {
                return _boxPeriod;
            }
            set
            {
                _boxPeriod = value;
            }
        }
    
        /// <summary>
        /// The period of the blinking of the central poke LED (ms).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("poke_period", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="poke_period")]
        [System.ComponentModel.DescriptionAttribute("The period of the blinking of the central poke LED (ms).")]
        public double PokePeriod
        {
            get
            {
                return _pokePeriod;
            }
            set
            {
                _pokePeriod = value;
            }
        }
    
        /// <summary>
        /// Indicates whether the box LED should turn of when the new trial is ready (true) or not (false).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("iti_light", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="iti_light")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the box LED should turn of when the new trial is ready (true) o" +
            "r not (false).")]
        public bool ItiLight
        {
            get
            {
                return _itiLight;
            }
            set
            {
                _itiLight = value;
            }
        }
    
        /// <summary>
        /// Indicates whether the central poke LED should turn of when the new trial is ready (true) or not (false).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("poke_light", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="poke_light")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the central poke LED should turn of when the new trial is ready" +
            " (true) or not (false).")]
        public bool PokeLight
        {
            get
            {
                return _pokeLight;
            }
            set
            {
                _pokeLight = value;
            }
        }
    
        /// <summary>
        /// Indicates whether the central poke LED should blink during fixation time (true) or not (false).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("fixation_light", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="fixation_light")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the central poke LED should blink during fixation time (true) o" +
            "r not (false).")]
        public bool FixationLight
        {
            get
            {
                return _fixationLight;
            }
            set
            {
                _fixationLight = value;
            }
        }
    
        /// <summary>
        /// Indicates whether the box LED should blink during penalty times (true) or not (false).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("penalty_light", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="penalty_light")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the box LED should blink during penalty times (true) or not (fa" +
            "lse).")]
        public bool PenaltyLight
        {
            get
            {
                return _penaltyLight;
            }
            set
            {
                _penaltyLight = value;
            }
        }
    
        public System.IObservable<Lights> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Lights(this)));
        }
    
        public System.IObservable<Lights> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Lights(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("BoxPeriod = " + _boxPeriod + ", ");
            stringBuilder.Append("PokePeriod = " + _pokePeriod + ", ");
            stringBuilder.Append("ItiLight = " + _itiLight + ", ");
            stringBuilder.Append("PokeLight = " + _pokeLight + ", ");
            stringBuilder.Append("FixationLight = " + _fixationLight + ", ");
            stringBuilder.Append("PenaltyLight = " + _penaltyLight);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Poke
    {
    
        private bool _lowToHigh;
    
        public Poke()
        {
        }
    
        protected Poke(Poke other)
        {
            _lowToHigh = other._lowToHigh;
        }
    
        /// <summary>
        /// Indicates whether the poke is a low-to-high (true) or a high-to-low (false) device.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("low_to_high", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="low_to_high")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the poke is a low-to-high (true) or a high-to-low (false) devic" +
            "e.")]
        public bool LowToHigh
        {
            get
            {
                return _lowToHigh;
            }
            set
            {
                _lowToHigh = value;
            }
        }
    
        public System.IObservable<Poke> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Poke(this)));
        }
    
        public System.IObservable<Poke> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Poke(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("LowToHigh = " + _lowToHigh);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Speakers
    {
    
        private double _leftSlope;
    
        private double _leftIntercept;
    
        private double _rightSlope;
    
        private double _rightIntercept;
    
        public Speakers()
        {
        }
    
        protected Speakers(Speakers other)
        {
            _leftSlope = other._leftSlope;
            _leftIntercept = other._leftIntercept;
            _rightSlope = other._rightSlope;
            _rightIntercept = other._rightIntercept;
        }
    
        /// <summary>
        /// The slope of the calibration curve of the left speaker.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("left_slope", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="left_slope")]
        [System.ComponentModel.DescriptionAttribute("The slope of the calibration curve of the left speaker.")]
        public double LeftSlope
        {
            get
            {
                return _leftSlope;
            }
            set
            {
                _leftSlope = value;
            }
        }
    
        /// <summary>
        /// The intercept of the calibration curve of the left speaker.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("left_intercept", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="left_intercept")]
        [System.ComponentModel.DescriptionAttribute("The intercept of the calibration curve of the left speaker.")]
        public double LeftIntercept
        {
            get
            {
                return _leftIntercept;
            }
            set
            {
                _leftIntercept = value;
            }
        }
    
        /// <summary>
        /// The slope of the calibration curve of the right speaker.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("right_slope", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="right_slope")]
        [System.ComponentModel.DescriptionAttribute("The slope of the calibration curve of the right speaker.")]
        public double RightSlope
        {
            get
            {
                return _rightSlope;
            }
            set
            {
                _rightSlope = value;
            }
        }
    
        /// <summary>
        /// The intercept of the calibration curve of the right speaker.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("right_intercept", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="right_intercept")]
        [System.ComponentModel.DescriptionAttribute("The intercept of the calibration curve of the right speaker.")]
        public double RightIntercept
        {
            get
            {
                return _rightIntercept;
            }
            set
            {
                _rightIntercept = value;
            }
        }
    
        public System.IObservable<Speakers> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Speakers(this)));
        }
    
        public System.IObservable<Speakers> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Speakers(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("LeftSlope = " + _leftSlope + ", ");
            stringBuilder.Append("LeftIntercept = " + _leftIntercept + ", ");
            stringBuilder.Append("RightSlope = " + _rightSlope + ", ");
            stringBuilder.Append("RightIntercept = " + _rightIntercept);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class SyringePumps
    {
    
        private bool _usePumps;
    
        private double _leftSlope;
    
        private double _leftIntercept;
    
        private double _rightSlope;
    
        private double _rightIntercept;
    
        public SyringePumps()
        {
        }
    
        protected SyringePumps(SyringePumps other)
        {
            _usePumps = other._usePumps;
            _leftSlope = other._leftSlope;
            _leftIntercept = other._leftIntercept;
            _rightSlope = other._rightSlope;
            _rightIntercept = other._rightIntercept;
        }
    
        /// <summary>
        /// Indicates whether the setup uses valves (false) or Harp SyringePumps (true) for reward delivery.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("use_pumps", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="use_pumps")]
        [System.ComponentModel.DescriptionAttribute("Indicates whether the setup uses valves (false) or Harp SyringePumps (true) for r" +
            "eward delivery.")]
        public bool UsePumps
        {
            get
            {
                return _usePumps;
            }
            set
            {
                _usePumps = value;
            }
        }
    
        /// <summary>
        /// The slope of the calibration curve of the left Harp SyringePump.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("left_slope", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="left_slope")]
        [System.ComponentModel.DescriptionAttribute("The slope of the calibration curve of the left Harp SyringePump.")]
        public double LeftSlope
        {
            get
            {
                return _leftSlope;
            }
            set
            {
                _leftSlope = value;
            }
        }
    
        /// <summary>
        /// The intercept of the calibration curve of the left Harp SyringePump.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("left_intercept", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="left_intercept")]
        [System.ComponentModel.DescriptionAttribute("The intercept of the calibration curve of the left Harp SyringePump.")]
        public double LeftIntercept
        {
            get
            {
                return _leftIntercept;
            }
            set
            {
                _leftIntercept = value;
            }
        }
    
        /// <summary>
        /// The slope of the calibration curve of the right Harp SyringePump.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("right_slope", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="right_slope")]
        [System.ComponentModel.DescriptionAttribute("The slope of the calibration curve of the right Harp SyringePump.")]
        public double RightSlope
        {
            get
            {
                return _rightSlope;
            }
            set
            {
                _rightSlope = value;
            }
        }
    
        /// <summary>
        /// The intercept of the calibration curve of the right Harp SyringePump.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("right_intercept", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="right_intercept")]
        [System.ComponentModel.DescriptionAttribute("The intercept of the calibration curve of the right Harp SyringePump.")]
        public double RightIntercept
        {
            get
            {
                return _rightIntercept;
            }
            set
            {
                _rightIntercept = value;
            }
        }
    
        public System.IObservable<SyringePumps> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new SyringePumps(this)));
        }
    
        public System.IObservable<SyringePumps> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new SyringePumps(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("UsePumps = " + _usePumps + ", ");
            stringBuilder.Append("LeftSlope = " + _leftSlope + ", ");
            stringBuilder.Append("LeftIntercept = " + _leftIntercept + ", ");
            stringBuilder.Append("RightSlope = " + _rightSlope + ", ");
            stringBuilder.Append("RightIntercept = " + _rightIntercept);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Setup
    {
    
        private int _setupId;
    
        private Poke _leftPoke;
    
        private Poke _centerPoke;
    
        private Poke _rightPoke;
    
        private Speakers _speakers;
    
        private Lights _lights;
    
        private SyringePumps _syringePumps;
    
        private System.Collections.Generic.List<int> _sounds;
    
        private System.Collections.Generic.List<int> _shortSounds;
    
        private Camera _camera;
    
        public Setup()
        {
            _leftPoke = new Poke();
            _centerPoke = new Poke();
            _rightPoke = new Poke();
            _speakers = new Speakers();
            _lights = new Lights();
            _syringePumps = new SyringePumps();
            _sounds = new System.Collections.Generic.List<int>();
            _shortSounds = new System.Collections.Generic.List<int>();
            _camera = new Camera();
        }
    
        protected Setup(Setup other)
        {
            _setupId = other._setupId;
            _leftPoke = other._leftPoke;
            _centerPoke = other._centerPoke;
            _rightPoke = other._rightPoke;
            _speakers = other._speakers;
            _lights = other._lights;
            _syringePumps = other._syringePumps;
            _sounds = other._sounds;
            _shortSounds = other._shortSounds;
            _camera = other._camera;
        }
    
        /// <summary>
        /// The ID number of the setup.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("setup_id", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="setup_id")]
        [System.ComponentModel.DescriptionAttribute("The ID number of the setup.")]
        public int SetupId
        {
            get
            {
                return _setupId;
            }
            set
            {
                _setupId = value;
            }
        }
    
        /// <summary>
        /// Contains parameters related to the left poke.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("left_poke", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="left_poke")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the left poke.")]
        public Poke LeftPoke
        {
            get
            {
                return _leftPoke;
            }
            set
            {
                _leftPoke = value;
            }
        }
    
        /// <summary>
        /// Contains parameters related to the center poke.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("center_poke", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="center_poke")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the center poke.")]
        public Poke CenterPoke
        {
            get
            {
                return _centerPoke;
            }
            set
            {
                _centerPoke = value;
            }
        }
    
        /// <summary>
        /// Contains parameters related to the right poke.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("right_poke", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="right_poke")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the right poke.")]
        public Poke RightPoke
        {
            get
            {
                return _rightPoke;
            }
            set
            {
                _rightPoke = value;
            }
        }
    
        /// <summary>
        /// Contains parameters related to the speakers.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("speakers", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="speakers")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the speakers.")]
        public Speakers Speakers
        {
            get
            {
                return _speakers;
            }
            set
            {
                _speakers = value;
            }
        }
    
        /// <summary>
        /// Contains parameters related to the box and poke LEDs.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("lights", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="lights")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the box and poke LEDs.")]
        public Lights Lights
        {
            get
            {
                return _lights;
            }
            set
            {
                _lights = value;
            }
        }
    
        /// <summary>
        /// Contains the parameters related to the SyringePumps.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("syringe_pumps", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="syringe_pumps")]
        [System.ComponentModel.DescriptionAttribute("Contains the parameters related to the SyringePumps.")]
        public SyringePumps SyringePumps
        {
            get
            {
                return _syringePumps;
            }
            set
            {
                _syringePumps = value;
            }
        }
    
        /// <summary>
        /// The list containing the indexes where the non-short-duration sounds are saved in the Harp SoundCard.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("sounds", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="sounds")]
        [System.ComponentModel.DescriptionAttribute("The list containing the indexes where the non-short-duration sounds are saved in " +
            "the Harp SoundCard.")]
        public System.Collections.Generic.List<int> Sounds
        {
            get
            {
                return _sounds;
            }
            set
            {
                _sounds = value;
            }
        }
    
        /// <summary>
        /// The list containing the indexes where the short-duration sounds are saved in the Harp SoundCard.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("short_sounds", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="short_sounds")]
        [System.ComponentModel.DescriptionAttribute("The list containing the indexes where the short-duration sounds are saved in the " +
            "Harp SoundCard.")]
        public System.Collections.Generic.List<int> ShortSounds
        {
            get
            {
                return _shortSounds;
            }
            set
            {
                _shortSounds = value;
            }
        }
    
        /// <summary>
        /// Contains parameters related to the camera.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("camera", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="camera")]
        [System.ComponentModel.DescriptionAttribute("Contains parameters related to the camera.")]
        public Camera Camera
        {
            get
            {
                return _camera;
            }
            set
            {
                _camera = value;
            }
        }
    
        public System.IObservable<Setup> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Setup(this)));
        }
    
        public System.IObservable<Setup> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Setup(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("SetupId = " + _setupId + ", ");
            stringBuilder.Append("LeftPoke = " + _leftPoke + ", ");
            stringBuilder.Append("CenterPoke = " + _centerPoke + ", ");
            stringBuilder.Append("RightPoke = " + _rightPoke + ", ");
            stringBuilder.Append("Speakers = " + _speakers + ", ");
            stringBuilder.Append("Lights = " + _lights + ", ");
            stringBuilder.Append("SyringePumps = " + _syringePumps + ", ");
            stringBuilder.Append("Sounds = " + _sounds + ", ");
            stringBuilder.Append("ShortSounds = " + _shortSounds + ", ");
            stringBuilder.Append("Camera = " + _camera);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum CameraType
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Point Grey")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Point Grey")]
        PointGrey = 0,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="FLIR")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="FLIR")]
        FLIR = 1,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum CameraCodec
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="h264")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="h264")]
        H264 = 0,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="h264_amf")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="h264_amf")]
        H264Amf = 1,
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToJson
    {
    
        public Newtonsoft.Json.Formatting Formatting { get; set; }

        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            var formatting = Formatting;
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value, formatting));
        }

        public System.IObservable<string> Process(System.IObservable<Camera> source)
        {
            return Process<Camera>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Lights> source)
        {
            return Process<Lights>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Poke> source)
        {
            return Process<Poke>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Speakers> source)
        {
            return Process<Speakers>(source);
        }

        public System.IObservable<string> Process(System.IObservable<SyringePumps> source)
        {
            return Process<SyringePumps>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Setup> source)
        {
            return Process<Setup>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Camera>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Lights>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Poke>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Speakers>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<SyringePumps>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Setup>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<Setup>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<Camera> source)
        {
            return Process<Camera>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Lights> source)
        {
            return Process<Lights>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Poke> source)
        {
            return Process<Poke>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Speakers> source)
        {
            return Process<Speakers>(source);
        }

        public System.IObservable<string> Process(System.IObservable<SyringePumps> source)
        {
            return Process<SyringePumps>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Setup> source)
        {
            return Process<Setup>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Camera>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Lights>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Poke>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Speakers>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<SyringePumps>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Setup>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<Setup>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}