### YamlMime:ManagedReference
items:
- uid: Training
  commentId: N:Training
  id: Training
  children:
  - Training.ABL
  - Training.CriticalPerformance
  - Training.Cues
  - Training.DeserializeFromJson
  - Training.DeserializeFromYaml
  - Training.FixationTime
  - Training.ILD
  - Training.ITI
  - Training.Level
  - Training.PenaltyTimes
  - Training.ReactionTime
  - Training.SerializeToJson
  - Training.SerializeToYaml
  - Training.Sound
  - Training.Training
  - Training.TrialRepetition
  langs:
  - csharp
  - vb
  name: Training
  nameWithType: Training
  fullName: Training
  type: Namespace
  assemblies:
  - Extensions
references:
- uid: Training.ABL
  commentId: T:Training.ABL
  parent: Training
  href: Training.ABL.html
  name: ABL
  nameWithType: ABL
  fullName: Training.ABL
- uid: Training.CriticalPerformance
  commentId: T:Training.CriticalPerformance
  parent: Training
  href: Training.CriticalPerformance.html
  name: CriticalPerformance
  nameWithType: CriticalPerformance
  fullName: Training.CriticalPerformance
- uid: Training.Cues
  commentId: T:Training.Cues
  parent: Training
  href: Training.Cues.html
  name: Cues
  nameWithType: Cues
  fullName: Training.Cues
- uid: Training.FixationTime
  commentId: T:Training.FixationTime
  parent: Training
  href: Training.FixationTime.html
  name: FixationTime
  nameWithType: FixationTime
  fullName: Training.FixationTime
- uid: Training.ILD
  commentId: T:Training.ILD
  parent: Training
  href: Training.ILD.html
  name: ILD
  nameWithType: ILD
  fullName: Training.ILD
- uid: Training.ITI
  commentId: T:Training.ITI
  parent: Training
  href: Training.ITI.html
  name: ITI
  nameWithType: ITI
  fullName: Training.ITI
- uid: Training.Level
  commentId: T:Training.Level
  parent: Training
  href: Training.Level.html
  name: Level
  nameWithType: Level
  fullName: Training.Level
- uid: Training.PenaltyTimes
  commentId: T:Training.PenaltyTimes
  parent: Training
  href: Training.PenaltyTimes.html
  name: PenaltyTimes
  nameWithType: PenaltyTimes
  fullName: Training.PenaltyTimes
- uid: Training.ReactionTime
  commentId: T:Training.ReactionTime
  parent: Training
  href: Training.ReactionTime.html
  name: ReactionTime
  nameWithType: ReactionTime
  fullName: Training.ReactionTime
- uid: Training.Sound
  commentId: T:Training.Sound
  parent: Training
  href: Training.Sound.html
  name: Sound
  nameWithType: Sound
  fullName: Training.Sound
- uid: Training.TrialRepetition
  commentId: T:Training.TrialRepetition
  parent: Training
  href: Training.TrialRepetition.html
  name: TrialRepetition
  nameWithType: TrialRepetition
  fullName: Training.TrialRepetition
- uid: Training.Training
  commentId: T:Training.Training
  parent: Training
  href: Training.Training.html
  name: Training
  nameWithType: Training
  fullName: Training.Training
- uid: Training.SerializeToJson
  commentId: T:Training.SerializeToJson
  href: Training.SerializeToJson.html
  name: SerializeToJson
  nameWithType: SerializeToJson
  fullName: Training.SerializeToJson
- uid: Training.DeserializeFromJson
  commentId: T:Training.DeserializeFromJson
  href: Training.DeserializeFromJson.html
  name: DeserializeFromJson
  nameWithType: DeserializeFromJson
  fullName: Training.DeserializeFromJson
- uid: Training.SerializeToYaml
  commentId: T:Training.SerializeToYaml
  href: Training.SerializeToYaml.html
  name: SerializeToYaml
  nameWithType: SerializeToYaml
  fullName: Training.SerializeToYaml
- uid: Training.DeserializeFromYaml
  commentId: T:Training.DeserializeFromYaml
  href: Training.DeserializeFromYaml.html
  name: DeserializeFromYaml
  nameWithType: DeserializeFromYaml
  fullName: Training.DeserializeFromYaml
- uid: Training
  commentId: N:Training
  href: Training.html
  name: Training
  nameWithType: Training
  fullName: Training
